name: 'Create Release'

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: build
        name: 'Build'
        run: |
          # printf '%s\n' "${{ github.sha }}" > ./Release;

          mkdir -- /opt/release;
          cd -- /opt/release/;

          bash -- "${GITHUB_WORKSPACE}/.project/scripts/pack.sh" "${GITHUB_WORKSPACE}/HonestWrits.txt";

          ls -la;

      - id: release
        name: 'Release'
        uses: 'softprops/action-gh-release@v2'
        with:
          name: "Honest Writs ${{ github.ref_name }}"
          files: '/opt/release/*.zip'